name: Super-Linter

on:
  push:

jobs:
  super-lint:
    name: Lint Python code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v4.9.5
        env:
          VALIDATE_PYTHON: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  deploy:
    name: Notifcation Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # ... other deployment steps go here ...

      - name: Notify developers via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Replace with the SMTP server address for Gmail
          server_port: 587  # Replace with the appropriate SMTP server port
          username: ${{ secrets.EMAIL_USERNAME }}  # Add email username as a secret
          password: ${{ secrets.EMAIL_PASSWORD }}  # Add email password as a secreta
          subject: Deployment Notification
          body: |
            The deployment was ${{ job.status }}!
          from: vivek.ofc11@gmail.com  # Replace with the sender email address
          to: candycrush1419@gmail.com  # Replace with the recipient email address
