name: Super-Linter

on:
  push:

jobs:
  super-lint:
    name: Lint Python code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v4.9.5
        env:
          VALIDATE_PYTHON: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

