name: Super-Linter

on:
  push:

jobs:
  super-lint:
    name: Lint Python code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v4.9.5
        env:
          VALIDATE_PYTHON: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  deploy:
    name: Notifcation Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     

      - name: Notify developers via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  
          server_port: 587 
          username: ${{ secrets.EMAIL_USERNAME }} 
          password: ${{ secrets.EMAIL_PASSWORD }} 
          subject: Deployment Notification
          body: |
            The deployment was ${{ job.status }}!
          from: vivek.ofc11@gmail.com 
          to: candycrush1419@gmail.com  
